### ISSUE TITLE
If there is any issue when contacting repeater it will crash homebridge

### ISSUE THREAD

**Issue by strifel** [lucavb/homebridge-http-motion-sensor#10]
Homebridge crashes completely when the connection to the receiver is not going well.

This should definitively be catched

**Comment by lucavb** [comment]
I assume by `when the connection to the receiver is not going well`, you mean if the receiver is unavailable?

**Comment by strifel** [comment]
I actually have a problem where node http thinks that the socket has been closed to early (cURL, wget, python requests all do not seem to think that).
Temporary fixed that by modifying the JS file manually to 
![image](https://user-images.githubusercontent.com/24608706/87883205-340b6d00-ca06-11ea-9d4c-0b8f6abc2527.png)

Your commit (0f1019e779b947de23b0c5b09dd37631bf778e07) seems to fix that.
Thanks!

**Comment by lucavb** [comment]
Alright, so then this should be fixed with the current version.
