### ISSUE TITLE
How does the triggering work ?

### ISSUE THREAD

**Issue by roe1974** [lucavb/homebridge-http-motion-sensor#2]
Hi

can i trigger this http-motion sensor from my edimax doorcam with http post ? (which hhtp string?)
how long the motion sensor will be "triggered" ? because the cam sends a http POST/GET comand when motion is detected ... but no comand when motion is over.....

regards, Richard

**Comment by lucavb** [comment]
This should be possible in general. Just point the camera to the IP address of your device and make sure to use the correct port number. The motion should then be triggered for 11 seconds of no new motion is detected. The requested URL is irrelevant. Any URL will suffice.

**Comment by roe1974** [comment]
just tested....works perfect !
thx !
richard

**Comment by jannnfe** [comment]
Can you explain how you get this work. I have a Wanscam and Foscam Camera and like to motion detection from this cameras

**Comment by roe1974** [comment]
The EDIMAX Cam has a Setup WebUI where i can config a http request (POST or GET) when PIR is active.
So every time the PIR sensor recognize a motion, a http POST event is executed.

**Comment by jannnfe** [comment]
Do you know to how to execute a URL Request on new Zoneminder Alarm?
