### ISSUE TITLE
Sensor with no detection

### ISSUE THREAD

**Issue by warcanoid** [lucavb/homebridge-http-motion-sensor#3]
I added the sensor in home app, but there always NO in Motion Detected.
This is from my config.json, I have also tried port 554 from rtsp stream, 465 from smtp,...:
	"accessories": [{
		"accessory": "http-motion-sensor",
		"name": "xyz Motion Sensor",
		"port": 8080,
		"serial": "",
		"repeater": [{
			"host": "192.168.1.3",
			"port": "8081",
			"path": "/turnonscreentilltimeout",
			"auth": "admin:password"
What should I do? Please help.

Regards W

**Comment by warcanoid** [comment]
I get this: 
pi@raspberrypi:~ $ curl localhost:
curl: (7) Failed to connect to localhost port 80: Connection refused
What means that?
Json in validated and works, I pasted it here bad.
Why is run homebridge as root dangerous? That why did not worked ports 554 and 465 when I started homebridge?
Thank you for helping!

**Comment by lucavb** [comment]
sorry, apparently GitHub removed the port specification. you have to add the port number used after the colon so something like curl localhost:23232 . 

Assuming there is a bug in homebridge or even my plugin, someone could take control over your computer and cause harm. And typically you don't need a privileged port for this kinda of thing. What are you using to trigger the sensor?

**Comment by warcanoid** [comment]
At the end I should add "curl localhost": "8080"?
To trigger the sensor, I use Tp-link camera with motion sensor and have added the snapshot address.

**Comment by lucavb** [comment]
No. I want you to run in your terminal within bash or whatever shell you are using "curl localhost:8080". This is not a parameter for the plugin.

And you don't need the repeater option either, if you don't want anything else to be called at the same time by the way.

**Comment by warcanoid** [comment]
Thank you for helping! I tried this now:
pi@raspberrypi:~ $ curl localhost:8080 homebridge
curl: (7) Failed to connect to localhost port 8080: Connection refused
and
pi@raspberrypi:~ $ homebridge curl localhost:8080
This works, but all is the same with no motion detected.
I got d-link dch-s150 motion sensor today.
Set new json, tried with curl localhost:8080, deleted also all from home, and perssist-accessories folders to start from new. Still nothing, this my new json, added serial from d-link:
          "accessories": [{
		"accessory": "http-motion-sensor",
		"name": "Senzor",
		"port": 8080,
		"serial": "serial from d-link"
	}],

**Comment by lucavb** [comment]
So if curl:8080 isn't working than you should make sure that the plugin is properly detected and loaded. Check the logs of homebridge for any errors or warnings.

**Comment by warcanoid** [comment]
This is when I start homebridge: 
[2018-7-25 18:16:54] [Senzor] Motion sensor server listening on: http://<your ip goes here>:8080
[2018-7-25 18:16:54] xyz is running on port 44001.
Error loading client secret file, please follow the instructions in the README
xyz is camera, why is running on port 44001? Stream port is 554, snapshopt 8080.

**Comment by warcanoid** [comment]
@lucavb can not install again your plugin- token validation-other plugins works fine. Lets fix this and get paid, I am seriously

**Comment by warcanoid** [comment]
I tried many options in config.json, but keep going this message when starting homebridge:

[2018-7-28 10:09:01] [Senzor] Motion sensor server listening on: http://<your ip goes here>:8080

I think it is missing IP address? The plugin is now ok installed, accessory is found at start,...

**Comment by lucavb** [comment]
Hmm that is add. It should say something like "http://<your ip goes here>:8080". So running "curl localhost:8080" does not turn up any results?

**Comment by warcanoid** [comment]
Nothing:(
