### ISSUE TITLE
Limiting service to one network

### ISSUE THREAD

**Issue by helo-head** [lucavb/homebridge-http-motion-sensor#4]
My current implementation is using your service to provide motion detection from BlueIris (video application). It works reliably which is always a good thing :)

With that said, my server has both a private and public network. I would like to limit the http service to the private network. Obviously the current service was not written to support this but it would be nice addition in opinion. Maybe a config.json option that allows the ability to define the network address?

On another note the only oddity I have noted (I think it might be related to having two networks) is that it fires two (2) homekit notifications for each detection. After looking at the code its not obvious why this is happening.

**Comment by lucavb** [comment]
I just released a new version of the plugin to npm. Sorry for the delay. It know has a bind_ip property, which should be pretty self-explanatory. I didn't test it, though the changes are so simple that I have confidence it'll work. Could you let me know though if it worked?
