### ISSUE TITLE
Cannot read property "on" of undefined

### ISSUE THREAD

**Issue by busaku** [lucavb/homebridge-http-motion-sensor#9]
`TypeError: Cannot read property 'on' of undefined
May 12 22:31:20 raspberrypi homebridge[3930]:     at new HomebridgeHttpMotionSensor (/usr/local/lib/node_modules/homebridge-http-motion-sensor/dist/index.js:39:18)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
May 12 22:31:20 raspberrypi homebridge[3930]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
May 12 22:31:20 raspberrypi homebridge[3930]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)`

just after an update :(

**Comment by lucavb** [comment]
Could you check that you have the latest version of homebridge?

**Comment by busaku** [comment]
Dude, iam sorry.. solved ;)
